version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: localtalk-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localtalk
      TZ: UTC

  localstack:
    container_name: localtalk-localstack
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - SERVICES=s3
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"