version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: localtalk-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localtalk
      TZ: UTC