spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        timezone.default_storage: NORMALIZE_UTC
        jdbc.time_zone: UTC


datasource:
  hikari:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      pool-name: mysql-master-pool
      maximum-pool-size: 40
      minimum-idle: 30
      connection-timeout: 3000
      validation-timeout: 5000
      keepalive-time: 0
      max-lifetime: 1800000
      leak-detection-threshold: 0
      initialization-fail-timeout: 1
      data-source-properties:
        rewriteBatchedStatements: true

---
spring.config.activate.on-profile: local

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

datasource:
  hikari:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/localtalk
      username: root
      password: root

---
spring.config.activate.on-profile: test

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

datasource:
  hikari:
    master:
      maximum-pool-size: 10
      minimum-idle: 5

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    show-sql: true

datasource:
  hikari:
    master:
      jdbc-url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}


---
spring.config.activate.on-profile: prod

datasource:
  hikari:
    master:
      jdbc-url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}